version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satisfactory_saas_app
    ports:
      - "3001:3000"   # Expones el puerto 3000 del contenedor en el 3001 de la máquina
    depends_on:
      - db
    env_file:
      - .env         # Carga tus otras variables (GOOGLE_CLIENT_ID, NEXTAUTH_SECRET, etc.)
    environment:
      # Sobrescribe DATABASE_URL para que apunte al servicio 'db' en la red interna
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    networks:
      - saas_network

  db:
    image: postgres:14-alpine
    container_name: satisfactory_saas_db
    ports:
      - "5454:5432"  # Mapea el 5432 del contenedor al 5454 del host (para accesos fuera de Docker)
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas_network

volumes:
  postgres_data:

networks:
  saas_network:
    driver: bridge
