{{- if .Values.logging.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "satisfactory-saas.fullname" . }}-fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
    spec:
      serviceAccountName: fluent-bit # Requiere un ServiceAccount con permisos para leer pods y nodos
      containers:
        - name: fluent-bit
          image: "{{ .Values.logging.fluentBit.image }}"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: fluent-bit-config
          configMap:
            name: {{ include "satisfactory-saas.fullname" . }}-fluent-bit-config
  {{- end }}
