{{- if .Values.logging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "satisfactory-saas.fullname" . }}-fluent-bit-config
  labels:
    app.kubernetes.io/name: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Mem_Buf_Limit    5MB

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On

    [OUTPUT]
        Name            loki
        Match           *
        Url             http://loki-stack.loki.svc.cluster.local:3100/loki/api/v1/push
        BatchWait       1s
        BatchSize       102400 # 100KB
        Labels          {job="fluent-bit"}
        Label_Keys      $kubernetes['pod_name'],$kubernetes['namespace_name'],$kubernetes['container_name']
        Line_Format     json
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  {{- end }}
