{{- if .Values.tracing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satisfactory-saas.fullname" . }}-otel-collector
  labels:
    {{- include "satisfactory-saas.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.80.0
          command:
            - "/otelcol"
            - "--config=/conf/otel-collector-config.yaml"
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: {{ include "satisfactory-saas.fullname" . }}-otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "satisfactory-saas.fullname" . }}-otel-collector
  labels:
    {{- include "satisfactory-saas.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
  {{- end }}
